version: '3'

#The license file will be found under ./App_Data
#Configuration files (visualisation.config, NLog.config and Web.config) will be mounted from ./config

services:
  SenseAdapt_App:
    build: .
    image: senseadapt:latest
    ports:
      - 80:80
    volumes:
      - ./App_Data:/SenseAdapt/App_Data
      - ./config/visualisation.config:/SenseAdapt/visualisation.config:ro
      - ./config/NLog.config:/SenseAdapt/NLog.config:ro
      - ./config/Web.config:/SenseAdapt/Web.config:ro
    environment:
      MONO_ASPNET_WEBCONFIG_CACHESIZE: 2048
    restart: always
